
package com.example.demo.facturacionOperaciones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacionOperaciones", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacionOperaciones {


    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.VerificarComunicacionResponse")
    public Integer verificarComunicacion();

    /**
     * 
     * @param solicitudRegistroPuntoVenta
     * @return
     *     returns com.example.demo.facturacionOperaciones.RespuestaRegistroPuntoVenta
     */
    @WebMethod
    @WebResult(name = "RespuestaRegistroPuntoVenta", targetNamespace = "")
    @RequestWrapper(localName = "registroPuntoVenta", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.RegistroPuntoVenta")
    @ResponseWrapper(localName = "registroPuntoVentaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.RegistroPuntoVentaResponse")
    public RespuestaRegistroPuntoVenta registroPuntoVenta(
        @WebParam(name = "SolicitudRegistroPuntoVenta", targetNamespace = "")
        SolicitudRegistroPuntoVenta solicitudRegistroPuntoVenta);

    /**
     * 
     * @param solicitudRegFactRegularizacion
     * @return
     *     returns com.example.demo.facturacionOperaciones.RespuestaRegFactRegularizacion
     */
    @WebMethod
    @WebResult(name = "RespuestaRegFactRegularizacion", targetNamespace = "")
    @RequestWrapper(localName = "registroFacturasRegularizacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.RegistroFacturasRegularizacion")
    @ResponseWrapper(localName = "registroFacturasRegularizacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.RegistroFacturasRegularizacionResponse")
    public RespuestaRegFactRegularizacion registroFacturasRegularizacion(
        @WebParam(name = "SolicitudRegFactRegularizacion", targetNamespace = "")
        SolicitudRegFactRegularizacion solicitudRegFactRegularizacion);

    /**
     * 
     * @param solicitudOperaciones
     * @return
     *     returns com.example.demo.facturacionOperaciones.RespuestaCierreSistemas
     */
    @WebMethod
    @WebResult(name = "RespuestaCierreSistemas", targetNamespace = "")
    @RequestWrapper(localName = "cierreOperacionesSistema", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.CierreOperacionesSistema")
    @ResponseWrapper(localName = "cierreOperacionesSistemaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.CierreOperacionesSistemaResponse")
    public RespuestaCierreSistemas cierreOperacionesSistema(
        @WebParam(name = "SolicitudOperaciones", targetNamespace = "")
        SolicitudOperaciones solicitudOperaciones);

    /**
     * 
     * @param solicitudConsultaEvento
     * @return
     *     returns com.example.demo.facturacionOperaciones.RespuestaListaEventos
     */
    @WebMethod
    @WebResult(name = "RespuestaListaEventos", targetNamespace = "")
    @RequestWrapper(localName = "consultaEventoSignificativo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.ConsultaEventoSignificativo")
    @ResponseWrapper(localName = "consultaEventoSignificativoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.ConsultaEventoSignificativoResponse")
    public RespuestaListaEventos consultaEventoSignificativo(
        @WebParam(name = "SolicitudConsultaEvento", targetNamespace = "")
        SolicitudConsultaEvento solicitudConsultaEvento);

    /**
     * 
     * @param solicitudConsultaPuntoVenta
     * @return
     *     returns com.example.demo.facturacionOperaciones.RespuestaConsultaPuntoVenta
     */
    @WebMethod
    @WebResult(name = "RespuestaConsultaPuntoVenta", targetNamespace = "")
    @RequestWrapper(localName = "consultaPuntoVenta", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.ConsultaPuntoVenta")
    @ResponseWrapper(localName = "consultaPuntoVentaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.ConsultaPuntoVentaResponse")
    public RespuestaConsultaPuntoVenta consultaPuntoVenta(
        @WebParam(name = "SolicitudConsultaPuntoVenta", targetNamespace = "")
        SolicitudConsultaPuntoVenta solicitudConsultaPuntoVenta);

    /**
     * 
     * @param solicitudEventoSignificativo
     * @return
     *     returns com.example.demo.facturacionOperaciones.RespuestaListaEventos
     */
    @WebMethod
    @WebResult(name = "RespuestaListaEventos", targetNamespace = "")
    @RequestWrapper(localName = "registroEventoSignificativo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.RegistroEventoSignificativo")
    @ResponseWrapper(localName = "registroEventoSignificativoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.RegistroEventoSignificativoResponse")
    public RespuestaListaEventos registroEventoSignificativo(
        @WebParam(name = "SolicitudEventoSignificativo", targetNamespace = "")
        SolicitudEventoSignificativo solicitudEventoSignificativo);

    /**
     * 
     * @param solicitudCierrePuntoVenta
     * @return
     *     returns com.example.demo.facturacionOperaciones.RespuestaCierrePuntoVenta
     */
    @WebMethod
    @WebResult(name = "RespuestaCierrePuntoVenta", targetNamespace = "")
    @RequestWrapper(localName = "cierrePuntoVenta", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.CierrePuntoVenta")
    @ResponseWrapper(localName = "cierrePuntoVentaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacionOperaciones.CierrePuntoVentaResponse")
    public RespuestaCierrePuntoVenta cierrePuntoVenta(
        @WebParam(name = "SolicitudCierrePuntoVenta", targetNamespace = "")
        SolicitudCierrePuntoVenta solicitudCierrePuntoVenta);

}
