
package com.example.demo.operaciones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacionCodigos", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacionCodigos {


    /**
     * 
     * @param solicitudOperacionesCuis
     * @return
     *     returns com.example.demo.facturacion.RespuestaCuis
     */
    @WebMethod
    @WebResult(name = "RespuestaCuis", targetNamespace = "")
    @RequestWrapper(localName = "solicitudCuis", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.SolicitudCuis")
    @ResponseWrapper(localName = "solicitudCuisResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.SolicitudCuisResponse")
    public RespuestaCuis solicitudCuis(
        @WebParam(name = "SolicitudOperacionesCuis", targetNamespace = "")
        SolicitudOperacionesCuis solicitudOperacionesCuis);

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.VerificarComunicacionResponse")
    public Integer verificarComunicacion();

    /**
     * 
     * @param solicitudCuisMasivoSistemas
     * @return
     *     returns com.example.demo.facturacion.RespuestaCuisMasivo
     */
    @WebMethod
    @WebResult(name = "RespuestaCuisMasivo", targetNamespace = "")
    @RequestWrapper(localName = "solicitudCuisMasivo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.SolicitudCuisMasivo")
    @ResponseWrapper(localName = "solicitudCuisMasivoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.SolicitudCuisMasivoResponse")
    public RespuestaCuisMasivo solicitudCuisMasivo(
        @WebParam(name = "SolicitudCuisMasivoSistemas", targetNamespace = "")
        SolicitudCuisMasivoSistemas solicitudCuisMasivoSistemas);

    /**
     * 
     * @param solicitudOperaciones
     * @return
     *     returns com.example.demo.facturacion.RespuestaCufd
     */
    @WebMethod
    @WebResult(name = "RespuestaCufd", targetNamespace = "")
    @RequestWrapper(localName = "solicitudCufd", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.SolicitudCufd")
    @ResponseWrapper(localName = "solicitudCufdResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.SolicitudCufdResponse")
    public RespuestaCufd solicitudCufd(
        @WebParam(name = "SolicitudOperaciones", targetNamespace = "")
        SolicitudOperacionesCufd solicitudOperaciones);

    /**
     * 
     * @param solicitudMasivo
     * @return
     *     returns com.example.demo.facturacion.RespuestaCufdMasivo
     */
    @WebMethod
    @WebResult(name = "RespuestaCufdMasivo", targetNamespace = "")
    @RequestWrapper(localName = "solicitudCufdMasivo", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.SolicitudCufdMasivo")
    @ResponseWrapper(localName = "solicitudCufdMasivoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.SolicitudCufdMasivoResponse")
    public RespuestaCufdMasivo solicitudCufdMasivo(
        @WebParam(name = "SolicitudMasivo", targetNamespace = "")
        SolicitudMasivo solicitudMasivo);

    /**
     * 
     * @param solicitudNotificaRevocado
     * @return
     *     returns com.example.demo.facturacion.RespuestaNotificaRevocado
     */
    @WebMethod
    @WebResult(name = "RespuestaNotificaRevocado", targetNamespace = "")
    @RequestWrapper(localName = "notificaCertificadoRevocado", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.NotificaCertificadoRevocado")
    @ResponseWrapper(localName = "notificaCertificadoRevocadoResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.NotificaCertificadoRevocadoResponse")
    public RespuestaNotificaRevocado notificaCertificadoRevocado(
        @WebParam(name = "SolicitudNotificaRevocado", targetNamespace = "")
        SolicitudNotifcaRevocado solicitudNotificaRevocado);

}
