
package com.example.demo.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioAutenticacionSoap", targetNamespace = "https://siat.impuestos.gob.bo/ServicioAutenticacionSoap", wsdlLocation = "https://pilotosiatservicios.impuestos.gob.bo/v1/ServicioAutenticacionSoap?wsdl")
public class ServicioAutenticacionSoap_Service
    extends Service
{

    private final static URL SERVICIOAUTENTICACIONSOAP_WSDL_LOCATION;
    private final static WebServiceException SERVICIOAUTENTICACIONSOAP_EXCEPTION;
    private final static QName SERVICIOAUTENTICACIONSOAP_QNAME = new QName("https://siat.impuestos.gob.bo/ServicioAutenticacionSoap", "ServicioAutenticacionSoap");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://pilotosiatservicios.impuestos.gob.bo/v1/ServicioAutenticacionSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOAUTENTICACIONSOAP_WSDL_LOCATION = url;
        SERVICIOAUTENTICACIONSOAP_EXCEPTION = e;
    }

    public ServicioAutenticacionSoap_Service() {
        super(__getWsdlLocation(), SERVICIOAUTENTICACIONSOAP_QNAME);
    }

    public ServicioAutenticacionSoap_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOAUTENTICACIONSOAP_QNAME, features);
    }

    public ServicioAutenticacionSoap_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOAUTENTICACIONSOAP_QNAME);
    }

    public ServicioAutenticacionSoap_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOAUTENTICACIONSOAP_QNAME, features);
    }

    public ServicioAutenticacionSoap_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioAutenticacionSoap_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioAutenticacionSoap
     */
    @WebEndpoint(name = "AutenticacionSoapServiceImplPort")
    public ServicioAutenticacionSoap getAutenticacionSoapServiceImplPort() {
        return super.getPort(new QName("https://siat.impuestos.gob.bo/ServicioAutenticacionSoap", "AutenticacionSoapServiceImplPort"), ServicioAutenticacionSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioAutenticacionSoap
     */
    @WebEndpoint(name = "AutenticacionSoapServiceImplPort")
    public ServicioAutenticacionSoap getAutenticacionSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://siat.impuestos.gob.bo/ServicioAutenticacionSoap", "AutenticacionSoapServiceImplPort"), ServicioAutenticacionSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOAUTENTICACIONSOAP_EXCEPTION!= null) {
            throw SERVICIOAUTENTICACIONSOAP_EXCEPTION;
        }
        return SERVICIOAUTENTICACIONSOAP_WSDL_LOCATION;
    }

}
