
package com.example.demo.facturacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioFacturacion", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioFacturacion {


    /**
     * 
     * @param solicitudServicioRecepcionPaquete
     * @return
     *     returns com.example.demo.facturacion.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionPaqueteFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.RecepcionPaqueteFactura")
    @ResponseWrapper(localName = "recepcionPaqueteFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.RecepcionPaqueteFacturaResponse")
    public RespuestaRecepcion recepcionPaqueteFactura(
        @WebParam(name = "SolicitudServicioRecepcionPaquete", targetNamespace = "")
        SolicitudRecepcionPaquete solicitudServicioRecepcionPaquete);

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.VerificarComunicacionResponse")
    public Integer verificarComunicacion();

    /**
     * 
     * @param solicitudServicioRecepcionFactura
     * @return
     *     returns com.example.demo.facturacion.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.RecepcionFactura")
    @ResponseWrapper(localName = "recepcionFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.RecepcionFacturaResponse")
    public RespuestaRecepcion recepcionFactura(
        @WebParam(name = "SolicitudServicioRecepcionFactura", targetNamespace = "")
        SolicitudRecepcionFactura solicitudServicioRecepcionFactura);

    /**
     * 
     * @param solicitudServicioReversionAnulacionFactura
     * @return
     *     returns com.example.demo.facturacion.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "reversionAnulacionFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.ReversionAnulacionFactura")
    @ResponseWrapper(localName = "reversionAnulacionFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.ReversionAnulacionFacturaResponse")
    public RespuestaRecepcion reversionAnulacionFactura(
        @WebParam(name = "SolicitudServicioReversionAnulacionFactura", targetNamespace = "")
        SolicitudReversionAnulacion solicitudServicioReversionAnulacionFactura);

    /**
     * 
     * @param solicitudServicioValidacionRecepcionMasiva
     * @return
     *     returns com.example.demo.facturacion.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionMasivaFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.ValidacionRecepcionMasivaFactura")
    @ResponseWrapper(localName = "validacionRecepcionMasivaFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.ValidacionRecepcionMasivaFacturaResponse")
    public RespuestaRecepcion validacionRecepcionMasivaFactura(
        @WebParam(name = "SolicitudServicioValidacionRecepcionMasiva", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcionMasiva);

    /**
     * 
     * @param solicitudServicioRecepcionMasiva
     * @return
     *     returns com.example.demo.facturacion.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionMasivaFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.RecepcionMasivaFactura")
    @ResponseWrapper(localName = "recepcionMasivaFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.RecepcionMasivaFacturaResponse")
    public RespuestaRecepcion recepcionMasivaFactura(
        @WebParam(name = "SolicitudServicioRecepcionMasiva", targetNamespace = "")
        SolicitudRecepcionMasiva solicitudServicioRecepcionMasiva);

    /**
     * 
     * @param solicitudServicioVerificacionEstadoFactura
     * @return
     *     returns com.example.demo.facturacion.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "verificacionEstadoFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.VerificacionEstadoFactura")
    @ResponseWrapper(localName = "verificacionEstadoFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.VerificacionEstadoFacturaResponse")
    public RespuestaRecepcion verificacionEstadoFactura(
        @WebParam(name = "SolicitudServicioVerificacionEstadoFactura", targetNamespace = "")
        SolicitudVerificacionEstado solicitudServicioVerificacionEstadoFactura);

    /**
     * 
     * @param solicitudServicioValidacionRecepcionPaquete
     * @return
     *     returns com.example.demo.facturacion.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionPaqueteFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.ValidacionRecepcionPaqueteFactura")
    @ResponseWrapper(localName = "validacionRecepcionPaqueteFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.ValidacionRecepcionPaqueteFacturaResponse")
    public RespuestaRecepcion validacionRecepcionPaqueteFactura(
        @WebParam(name = "SolicitudServicioValidacionRecepcionPaquete", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcionPaquete);

    /**
     * 
     * @param solicitudServicioAnulacionFactura
     * @return
     *     returns com.example.demo.facturacion.RespuestaRecepcion
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "anulacionFactura", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.AnulacionFactura")
    @ResponseWrapper(localName = "anulacionFacturaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.example.demo.facturacion.AnulacionFacturaResponse")
    public RespuestaRecepcion anulacionFactura(
        @WebParam(name = "SolicitudServicioAnulacionFactura", targetNamespace = "")
        SolicitudAnulacion solicitudServicioAnulacionFactura);

}
