
package com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioAutenticacionSoap", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioAutenticacionSoap {


    /**
     * 
     * @param datosUsuarioRequest
     * @return
     *     returns com.UsuarioAutenticadoDto
     */
    @WebMethod
    @WebResult(name = "UsuarioAutenticadoDto", targetNamespace = "")
    @RequestWrapper(localName = "token", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.Token")
    @ResponseWrapper(localName = "tokenResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "com.TokenResponse")
    public UsuarioAutenticadoDto token(
        @WebParam(name = "DatosUsuarioRequest", targetNamespace = "")
        DatosUsuarioRequest datosUsuarioRequest);

}
